#!/bin/sh

set -e
set -x

echo 'itIsOKForACamelCaseWordToContainNumerousCOMPONENTS' | ${ASPELL} --camel-case -d en_US -a > tmp/res
if cat tmp/res | fgrep -x '-'; then
    echo "pass"
else
    echo "fail:"
    cat tmp/res
    exit 1
fi

echo 'EvenIfTheFirstCOMPONENTBeginsWithACapitalLetter' | ${ASPELL} --camel-case -d en_US -a > tmp/res
if cat tmp/res | fgrep -x '-'; then
    echo "pass"
else
    echo "fail:"
    cat tmp/res
    exit 1
fi

