#!/bin/sh

test -d interfaces || mkdir interfaces
test -d interfaces/cc || mkdir interfaces/cc
cd auto/
perl mk-src.pl
perl mk-doc.pl
touch auto
cd ..

autopoint -f || exit 1
libtoolize --automake || exit 1
aclocal -I m4 $ACLOCAL_FLAGS || exit 1
autoheader || exit 1
automake --add-missing --foreign || exit 1
autoconf || exit 1

