#!/bin/sh

mkdir -p build
cd build
../configure --enable-maintainer-mode --disable-shared --disable-pspell-compatibility \
  --prefix="`pwd`/../inst" CFLAGS='-g -O -Wall' CXXFLAGS='-g -O -Wall' "$@"



