#!/bin/sh

mkdir -p build
cd build
../configure --enable-maintainer-mode \
  --disable-shared --disable-pspell-compatibility\
  --prefix="`pwd`/../inst" CFLAGS='-g -Wall -Wno-unused' CXXFLAGS='-g -Wall -Wno-unused' "$@"
