.TH ASPELL-IMPORT 1 "2004-03-03" "GNU" "Aspell Abbreviated User's Manual"
.SH NAME
aspell-import \- import old personal dictionaries into GNU Aspell
.SH SYNOPSIS
.B aspell-import
.br
.SH DESCRIPTION
.B aspell-import
is a command that will search for old personal dictionaries and will
import them into GNU Aspell. It will look for both Ispell and Aspell
dictionaries. To use it just run it from the command prompt.
.SH OPTIONS
This program does not accept any command-line options.
.SH SEE ALSO
.PP
.BR aspell (1),
.BR run\-with\-aspell (1),
.BR word\-list\-compress (1)
.PP
The full documentation for
.BR Aspell
is maintained as a Texinfo manual
The 
.RB "`\|" aspell "\|'"
entry in
.B info
for more complete documentation.
.SH AUTHOR
This manual page was written by Brian Nelson <pyro@debian.org>.
