.TH PREZIP\-BIN 1 "2005-09-30" "prezip\-bin\-0.1.2" "Aspell Abbreviated User's Manual"
.SH NAME
prezip\-bin \- prefix zip delta word list compressor/decompressor
.SH SYNOPSIS
.B prezip\-bin
[ \fB\-V\fR | \fB\-d\fR | \fB\-z\fR ]
.SH DESCRIPTION
.B prezip\-bin
compresses/decompresses sorted word lists from standard input to
standard output.
.PP
.I Prezip\-bin
is similar to
.I word\-list\-compress(1)
but it allows a larger character set of
{0x00...0x09, 0x0B, 0x0C, 0x0E...0xFF} and multi\-words larger than 255
characters in length.  It can also decompress
.I word\-list\-compress(1)
compatible files.
.SH COMMANDS
.I Prezip\-bin
accepts only one of these commands.
.TP
\fB-V\fR
Display
.I prezip\-bin
version number to standard output.
.TP
\fB-d\fR
Read a compressed word list from standard input and decompress it to
standard output.  This can be a
.I word\-list\-compress(1)
or a
.I prezip\-bin
compressed file.
.TP
\fB-z\fR
Read a binary word list from standard input and compress it to
standard output.
.SH EXAMPLES
.TP
prezip\-bin \fB\-d\fR <wordlist.cwl >wordlist.txt
Decompress file wordlist.cwl to text file wordlist.txt
.TP
prezip\-bin \fB\-z\fR <wordlist.txt >wordlist.pz 2>errors.txt
Compress wordlist.txt to binary file wordlist.pz and send any error
messages to a text file named errors.txt
.TP
LC_COLLATE\=C sort \-u <wordlist.txt \fB|\fR prezip\-bin \-z >wordlist.pz
Sort a word list, then pipe it to
.I prezip\-bin
to create a compressed binary wordlist.pz file.
.TP
prezip\-bin \-d <words.pz \fB|\fR aspell create master ./words.rws
Decompress a wordlist, then pipe it to
.I aspell(1)
to create a spelling list.  Please check the
.I aspell(1)
info manual for proper usage and options.
.SH TIPS
.I Prezip\-bin
is best used with sorted word list type files.  It is not a general
purpose compression program since resulting files may actually
increase in size.
.PP
Unlike
.I word\-list\-compress(1)
if your word list has leading or trailing blank spaces for formatting
purposes, you should remove them first before you compress your list
using
.I prezip\-bin \-z
, otherwise those spaces will be included in the compressed binary
output.
.SH DIAGNOSTICS
.I Prezip\-bin
normally exits with a return code of 0. If it encounters an error,
a message is sent to standard error output (stderr), and
.I prezip\-bin
exits with a non-zero return value.  Error messages are listed below:
.TP
\fB(display help/usage message)\fR
Unknown command given on the command line so
.I prezip\-bin
displays a usage message to standard error output.
.TP
\fBunknown format\fR
The input file appears not to be an expected format, or may possibly be
a more advanced format.  The output file will be empty.
.TP
\fBcorrupt input\fR
This is only for the decompression command \fB\-d\fR. The input file
appeared to be of a correct format, but something appears wrong now.
There may be some valid data in output, but due to input corruption,
the rest of the file can not be completed.
.TP
\fBunexpected EOF\fR
The input file appeared okay but ended sooner than expected, therefore
the output file is not complete.
.SH SEE ALSO
.PP
.BR aspell (1),
.BR aspell\-import (1),
.BR run\-with\-aspell (1),
.BR word\-list\-compress (1)
.PP
Aspell is fully documented in its Texinfo manual.  See the
.RB "`\|" aspell "\|'"
entry in
.B info
for more complete documentation.
.SH REPORTING BUGS
For help, see the Aspell homepage at <http://aspell.net>.  Send bug
reports/comments to the Aspell user list at the above address.
.SH AUTHOR
This info page was written by Jose Da Silva <digital@joescat.com>.