.TH PSPELL\-CONFIG 1 "2004-03-02" "GNU" "Aspell Abbreviated User's Manual"
.SH NAME
pspell\-config \- prints information about a libpspell installation
.SH SYNOPSIS
.B pspell\-config
.I "[options]"
.br
.SH DESCRIPTION
.B pspell\-config
displays information about libpspell installation, mostly for use in
build scripts.  Note that this script is provided for backward
compatibility with programs that use pspell.  Do not use as it will
eventually go away.
.SH OPTIONS
.TP
.B "\-\-version"
outputs version information about the installed pspell
.TP
.B "\-\-datadir"
displays the data directory
.TP
.B "\-\-pkgdatadir"
displays the aspell package directory
.SH AUTHOR
This manual page was written by Brian Nelson <pyro@debian.org>.
