colour	color	1	61	color, cooler, collar, co lour, co-lour, col our, col-our, collier, colors, clout, lour, velour, cloud, colon, coolie, dolor, flour, Collier, clear, Clair, Colo, colder, calorie, closure, cloture, coleus, colony, colored, cool, glory, caller, cloy, clue, coir, coolers, Colon, col, color's, cor, cur, cools, floor, closer, clover, Cavour, Clojure, Closure, cola, coll, coolly, corr, cool's, recolor, Cole, COL, Clara, Clare, Col, Cooley, COLA, cooler's
hjk	hijack	1	55	hijack, hajj, hajji, haj, hack, hake, hawk, heck, hick, hike, hock, hoke, hook, hank, hark, honk, hulk, hunk, husk, jg, Gk, hag, hog, hug, hex, hgt, joke, Huck, Hank, kc, kg, HQ, Hg, haiku, hooky, jack, jock, Hakka, Hickok, jag, jig, jog, jug, khaki, Jake, hoick, hokey, KC, Hooke, Jack, Jock, hajj's, Hayek, HQ's, Hg's
hjkk	hijack	1	52	hijack, hajj, hajji, hulk, Hickok, hack, hake, hawk, heck, hick, hike, hock, hoke, hook, hank, hark, honk, hunk, husk, Hakka, haj, jack, jock, joke, Huck, Hank, jg, kc, kg, Gk, haiku, hoick, hokey, hooky, hag, hog, hug, jag, jig, jog, jug, khaki, Jack, Jake, Jock, hajj's, HQ, Hg, KC, Hayek, Hooke, Hakka's
jk	hijack	5	76	j, k, jg, joke, hijack, kc, kg, ck, wk, Gk, bk, jr, pk, jack, jock, jag, jig, jog, jug, Jake, KC, kike, JFK, Jack, Jock, cg, J, K, jokey, kick, kl, kook, keg, kw, Jo, km, ks, kt, AK, Bk, JD, JP, JV, Jr, Mk, OK, SK, UK, jerk, jink, junk, QC, jaw, jay, jct, jew, joy, pkg, cake, coke, KKK, Jacky, Keck, c, g, q, KO, KY, Ky, kW, KB, KP, KS, Kb, Kr, Ks
Hjk	Hijack	1	52	Hijack, Hajj, Hajji, Gk, Haj, Huck, Hack, Hake, Hawk, Heck, Hick, Hike, Hock, Hoke, Hook, Hank, Hark, Honk, Hulk, Hunk, Husk, Hg, Jg, Hakka, Hickok, Hag, Hog, Hug, Jake, Hex, Hgt, Joke, Kc, Kg, HQ, Hooke, Jack, Jock, Haiku, Hooky, Jag, Jig, Jog, Jug, Khaki, Hayek, Hoick, Hokey, KC, HQ's, Hg's, Hajj's
HJK	HIJACK	1	51	HIJACK, HAJJ, HAJJI, GK, HAJ, HUCK, HACK, HAKE, HAWK, HECK, HICK, HIKE, HOCK, HOKE, HOOK, HANK, HARK, HONK, HULK, HUNK, HUSK, HQ, HG, JG, HAKKA, HICKOK, HAG, HOG, HUG, JAKE, HEX, HGT, JOKE, KC, KG, HOOKE, JACK, JOCK, HAIKU, HOOKY, JAG, JIG, JOG, JUG, KHAKI, HAYEK, HOICK, HOKEY, HQ'S, HG'S, HAJJ'S
hk	hijack	1	62	hijack, h, k, haj, hake, hike, hoke, ck, ha, he, hi, ho, wk, HQ, Hg, bk, hf, hp, hr, ht, pk, hack, hawk, heck, hick, hock, hook, hag, hog, hug, Gk, Huck, H, K, kg, haiku, hokey, hooky, g, hgwy, j, kw, HI, Ha, He, Ho, kc, AK, Bk, HF, HM, HP, HR, HS, HT, Hf, Hz, Mk, OK, SK, UK, hank
sjk	hijack	1	44	hijack, sqq, SJ, SK, ska, ski, sky, SJW, sack, sake, seek, sick, soak, sock, souk, suck, sank, silk, sink, sulk, sunk, jg, scag, sq, sac, sag, sec, seq, sic, soc, Saki, SWAK, Saks, Salk, Sask, Sikh, Gk, SC, Sc, Sq, SAC, SEC, Sec, Soc
zphb	xenophobia	1	37	xenophobia, zephyr, fob, sob, zebu, sahib, soph, Zomba, fab, fib, sub, xv, SOB, Zibo, phobia, Sb, scab, slab, slob, snob, snub, stab, stub, swab, Feb, AFB, Saab, Serb, sf, FBI, SBA, Cebu, SF, Sophia, Sophie, Saiph, Sappho
