colour	color	1	61	color, cooler, collar, co lour, co-lour, col our, col-our, collier, colors, clout, lour, velour, cloud, colon, coolie, dolor, flour, Collier, clear, Clair, Colo, colder, calorie, closure, cloture, coleus, colony, colored, cool, glory, caller, cloy, clue, coir, coolers, Colon, col, color's, cor, cur, cools, floor, closer, clover, Cavour, Clojure, Closure, cola, coll, coolly, corr, cool's, recolor, Cole, COL, Clara, Clare, Col, Cooley, COLA, cooler's
hjk	hijack	1	73	hijack, hajj, hajji, Gk, haj, hack, hake, hawk, heck, hick, hike, hock, hoke, hook, hank, hark, honk, hulk, hunk, husk, jg, hag, hog, hug, hex, hgt, joke, Huck, Hank, kc, kg, HQ, Hg, haiku, hooky, jack, jock, Hakka, Hickok, h, j, jag, jig, jog, jug, k, khaki, Jake, hoick, hokey, KC, ck, ha, he, hi, ho, wk, Hooke, JFK, Jack, Jock, hajj's, H, J, K, Hayek, HI, Ha, He, Ho, Jo, HQ's, Hg's
hjkk	hijack	1	54	hijack, hajj, hajji, hulk, Hickok, hack, hake, hawk, heck, hick, hike, hock, hoke, hook, hank, hark, honk, hunk, husk, Hakka, Gk, haj, jack, jock, joke, Huck, Hank, jg, kc, kg, haiku, hoick, hokey, hooky, KKK, hag, hog, hug, jag, jig, jog, jug, khaki, Jack, Jake, Jock, hajj's, HQ, Hg, KC, Hayek, Hooke, JFK, Hakka's
jk	hijack	6	99	j, k, Gk, jg, joke, hijack, kc, kg, ck, wk, Bk, Mk, bk, jr, pk, jack, jock, jag, jig, jog, jug, Jake, KC, kike, JFK, Jack, Jock, QC, cg, J, K, Keck, jokey, kick, kl, kook, kW, keg, kw, Jo, km, ks, kt, AK, JD, JP, JV, Jr, OK, SK, UK, jerk, jink, junk, jaw, jay, jct, jew, joy, pkg, Coke, cake, coke, KKK, C, G, Jacky, Q, c, g, q, KO, KY, Ky, KB, KP, KS, Kb, Kr, Ks, Cook, cock, cook, gawk, geek, gook, DJ, NJ, OJ, SJ, VJ, EKG, JCS, Jay, Jew, Joe, Joy, J's, K's
Hjk	Hijack	1	64	Hijack, Hajj, Hajji, Gk, Haj, Huck, Hack, Hake, Hawk, Heck, Hick, Hike, Hock, Hoke, Hook, Hank, Hark, Honk, Hulk, Hunk, Husk, HQ, Hg, Hakka, Hickok, Hag, Hog, Hug, Hex, Hgt, Jg, Hooke, Haiku, Hooky, H, Jake, Joke, Hayek, Hoick, Hokey, HI, Ha, He, Ho, KC, Ck, Hi, Kc, Kg, Wk, HQ's, Hg's, JFK, Jack, Jock, Hajj's, J, K, Jag, Jig, Jog, Jug, Khaki, Jo
HJK	HIJACK	1	62	HIJACK, HAJJ, HAJJI, GK, HAJ, HUCK, HACK, HAKE, HAWK, HECK, HICK, HIKE, HOCK, HOKE, HOOK, HANK, HARK, HONK, HULK, HUNK, HUSK, HQ, HG, JG, HAKKA, HICKOK, HAG, HOG, HUG, JAKE, HEX, HGT, JOKE, KC, KG, HOOKE, JFK, JACK, JOCK, HAIKU, HOOKY, H, J, K, JAG, JIG, JOG, JUG, KHAKI, HAYEK, HOICK, HOKEY, HI, HA, HE, HO, JO, CK, WK, HQ'S, HG'S, HAJJ'S
hk	hijack	1	105	hijack, Gk, h, k, haj, hake, hike, hoke, ck, ha, he, hi, ho, wk, Bk, HQ, Hg, Mk, bk, hf, hp, hr, ht, pk, hack, hawk, heck, hick, hock, hook, hag, hog, hug, Huck, H, K, kg, haiku, hokey, hooky, G, J, g, hgwy, j, kW, kw, HI, Ha, He, Ho, kc, AK, HF, HM, HP, HR, HS, HT, Hf, Hz, OK, SK, UK, hank, hark, honk, hulk, hunk, husk, hoick, haw, hay, hew, hex, hey, hgt, hie, hoe, how, hue, hwy, h'm, huge, C, Hakka, Hooke, Q, c, q, KO, KY, Ky, KC, Hank, Hayek, Haw, Hay, Hui, H's, Hugo, GHQ, KKK, Hg's, HQ's
sjk	hijack	1	44	hijack, sqq, SJ, SK, ska, ski, sky, SJW, sack, sake, seek, sick, soak, sock, souk, suck, sank, silk, sink, sulk, sunk, Gk, jg, scag, sq, sac, sag, sec, seq, sic, soc, Saki, SWAK, Saks, Salk, Sask, Sikh, SC, Sc, Sq, SAC, SEC, Sec, Soc
zphb	xenophobia	1	107	xenophobia, zephyr, fob, sob, zebu, Sb, phi, kph, mph, pub, sahib, soph, Feb, Zomba, fab, fib, sub, xv, SOB, Zibo, hob, pH, Pb, phobia, Saab, Serb, scab, slab, slob, snob, snub, stab, stub, swab, Ob, hub, ob, zap, zip, PHP, PhD, APB, PCB, b, z, phis, phys, AFB, phew, zoo, chub, phat, Cebu, Cb, Kb, Mb, Nb, Rb, Sp, Tb, Yb, ab, db, hf, lb, pf, tb, vb, GB, HBO, Heb, OB, SF, Sophia, Sophie, Zn, sf, Caph, Saiph, B, FBI, SBA, Z, psi, Zoe, Phil, Sappho, BB, AB, CB, HF, Hf, KB, MB, NB, QB, TB, Zr, Zs, dB, BBB, GHz, SPF, USB, Zzz, Z's, phi's
