colour	color	1	19	color, cooler, collar, coLour, colOur, Collier, collier, Clair, clear, calorie, colliery, glory, caller, Claire, Clara, Clare, jollier, jowlier, galore
hjk	hijack	1	4	hijack, hajj, hajji, Hickok
hjkk	hijack	1	4	hijack, hajj, Hickok, hajji
jk	hijack	10	57	JFK, J, K, j, k, Gk, jg, Jake, joke, hijack, KC, kc, kg, Jo, ck, wk, AK, Bk, JD, JP, JV, Jr, Mk, OK, SK, UK, bk, jr, pk, Jack, Jock, jack, jock, jag, jig, jog, jug, kike, QC, cg, jK, Jacky, Keck, jokey, kick, kook, keg, Coke, J's, cake, coke, Cook, cock, cook, gawk, geek, gook
Hjk	Hijack	1	4	Hijack, Hajj, Hajji, Hickok
HJK	HIJACK	1	4	HIJACK, HAJJ, HAJJI, HICKOK
hk	hijack	1	65	hijack, Gk, H, K, h, k, HQ, Hg, haj, hake, hike, hoke, HI, Ha, He, Ho, ck, ha, he, hi, ho, wk, AK, Bk, HF, HM, HP, HR, HS, HT, Hf, Hz, Mk, OK, SK, UK, bk, hf, hp, hr, ht, pk, Huck, hack, hawk, heck, hick, hock, hook, hag, hog, hug, hK, Hakka, Hooke, haiku, hokey, hooky, hgwy, Hayek, hoick, H's, Hugo, h'm, huge
sjk	hijack	4	6	SJ, SK, SJW, hijack, sqq, scag
zphb	xenophobia	1	1	xenophobia
zkw	zip line	1	22	zip line, kW, kw, Zeke, SJW, Zika, skew, SK, ska, ski, sky, zKw, SJ, Sq, sq, xx, sake, skua, SC, Sc, Saki, scow
Joeuser	JoeUser	1	15	JoeUser, Geyser, Causer, Guesser, Kaiser, Kisser, Juicer, Cozier, Queasier, Juicier, Caesar, Gasser, Coaxer, Geezer, Jazzier
JoeuSer	JoeUser	1	15	JoeUser, Geyser, Causer, Guesser, Kaiser, Kisser, Juicer, Cozier, Queasier, Juicier, Caesar, Gasser, Coaxer, Geezer, Jazzier
JooUser	JoeUser	2	53	JoUser, JoeUser, JoyUser, CooUser, GooUser, KOUser, JobUser, JonUser, JogUser, JotUser, BooUser, FooUser, LooUser, MooUser, PooUser, TooUser, WooUser, ZooUser, JUser, JoeyUser, COUser, CoUser, GoUser, CoyUser, GAOUser, GeoUser, GoaUser, JayUser, JewUser, CowUser, JawUser, QuoUser, JoOUser, Jo'sUser, Causer, Juicer, Kaiser, Kisser, Cozier, Geyser, Juicier, Gasser, Coaxer, Guesser, Jazzier, Gassier, Quasar, Causerie, Gauzier, Gazer, Queasier, Caesar, Geezer
camelCasWord	camelCaseWord	3	100	camelCSSWord, camelCa'sWord, camelCaseWord, camelCawsWord, camelCaysWord, camelCabsWord, camelCadsWord, camelCamsWord, camelCansWord, camelCapsWord, camelCarsWord, camelCaskWord, camelCastWord, camelCatsWord, camelCADWord, camelCashWord, camelCsWord, camelCadWord, camelAsWord, camelCAWord, camelCaWord, camelC'sWord, camelCosWord, camelGasWord, camelCaSword, camelCauseWord, camelCussWord, camelCAIWord, camelCBSWord, camelCDsWord, camelCNSWord, camelCVSWord, camelCawWord, camelCayWord, camelCpsWord, camelCAMWord, camelCAPWord, camelCalWord, camelCanWord, camelLasWord, camelOASWord, camelCabWord, camelCamWord, camelCapWord, camelCarWord, camelCatWord, camelHasWord, camelMasWord, camelPasWord, camelWasWord, camelCaseyWord, camelGSAWord, camelCaw'sWord, camelCay'sWord, camelCO'sWord, camelCo'sWord, camelCu'sWord, camelGa'sWord, camelCoaxWord, camelCoosWord, camelCowsWord, camelCuesWord, camelGaysWord, camelJawsWord, camelJaysWord, camelCZWord, camelKSWord, camelKsWord, camelGsWord, camelCSS'sWord, camelCos'sWord, camelCoxWord, camelG'sWord, camelGusWord, camelJ'sWord, camelK'sWord, camelCAsWord, camelCaSWord, camelCPA'sWord, camelCIA'sWord, camelVa'sWord, camelGas'sWord, camelA'sWord, camelAC'sWord, camelAc'sWord, camelCAD'sWord, camelCal'sWord, camelCan'sWord, camelRCA'sWord, camelCab'sWord, camelCad'sWord, camelCam'sWord, camelCap'sWord, camelCar'sWord, camelCat'sWord, camelCD'sWord, camelCT'sWord, camelCd'sWord, camelCf'sWord, camelCl'sWord
camelcaseWord	camelCaseWord	1	3	camelCaseWord, Gomulka'sWord, gemology'sWord
cmlCaseWord	camelCaseWord	8	22	XMLCaseWord, ClCaseWord, CmCaseWord, clCaseWord, cmCaseWord, mlCaseWord, CamelCaseWord, camelCaseWord, COLCaseWord, CalCaseWord, ColCaseWord, calCaseWord, colCaseWord, CplCaseWord, cplCaseWord, comelyCaseWord, cumuliCaseWord, cMlCaseWord, cmLCaseWord, Cm'sCaseWord, JamalCaseWord, JamelCaseWord
mcdonalds	McDonald's	1	3	McDonald's, McDonald, MacDonald's
