colour	color	1	61	color, cooler, collar, co lour, co-lour, col our, col-our, colors, Colo, lour, Collier, collier, Colon, cloud, clout, colon, dolor, flour, Clair, clear, colder, Cavour, Clojure, Closure, closure, cloture, coleus, colony, velour, cool, caller, coolers, COL, Clara, Clare, Col, col, color's, colored, cor, cur, glory, cools, floor, closer, clover, calorie, COLA, Cole, Cooley, cloy, clue, coir, cola, coll, coolie, coolly, corr, cool's, recolor, cooler's
hjk	hijack	1	55	hijack, hajj, haj, Huck, hack, hake, hawk, heck, hick, hike, hock, hoke, hook, Hank, hajji, hank, hark, honk, hulk, hunk, husk, Gk, HQ, Hg, jg, hag, hog, hug, Jake, hex, hgt, joke, KC, kc, kg, Hakka, Hooke, haiku, hooky, Jack, Jock, jack, jock, jag, jig, jog, jug, khaki, Hayek, hoick, hokey, Hickok, HQ's, Hg's, hajj's
hjkk	hijack	1	52	hijack, Hickok, hajj, Hakka, hajji, Huck, hack, hake, hawk, heck, hick, hike, hock, hoke, hook, Hank, hank, hark, honk, hulk, hunk, husk, haj, Jack, Jake, Jock, jack, jock, joke, Gk, HQ, Hg, KC, jg, kc, kg, Hayek, Hooke, haiku, hoick, hokey, hooky, hag, hog, hug, jag, jig, jog, jug, khaki, Hakka's, hajj's
jk	hijack	10	99	JFK, J, K, j, k, Gk, jg, Jake, joke, hijack, KC, kc, kg, Jo, ck, wk, AK, Bk, JD, JP, JV, Jr, Mk, OK, SK, UK, bk, jr, pk, Jack, Jock, jack, jock, jag, jig, jog, jug, QC, cg, Jacky, jokey, KO, KY, Ky, kW, kw, KB, KP, KS, Kb, Kr, Ks, keg, kl, km, ks, kt, jerk, jink, junk, DJ, NJ, OJ, SJ, VJ, EKG, JCS, Jay, Jew, Joe, Joy, jaw, jay, jct, jew, joy, pkg, Coke, J's, cake, coke, kike, C, G, Q, c, g, q, KKK, Cook, Keck, cock, cook, gawk, geek, gook, kick, kook, K's
Hjk	Hijack	1	52	Hijack, Hajj, Haj, Huck, Hack, Hake, Hawk, Heck, Hick, Hike, Hock, Hoke, Hook, Hank, Hajji, Hark, Honk, Hulk, Hunk, Husk, Gk, HQ, Hg, Jg, Hag, Hog, Hug, Jake, Hex, Hgt, Joke, KC, Kc, Kg, Hakka, Hooke, Haiku, Hooky, Jack, Jock, Jag, Jig, Jog, Jug, Khaki, Hayek, Hoick, Hokey, Hickok, HQ's, Hg's, Hajj's
HJK	HIJACK	1	51	HIJACK, HAJJ, HAJ, HUCK, HACK, HAKE, HAWK, HECK, HICK, HIKE, HOCK, HOKE, HOOK, HANK, HAJJI, HARK, HONK, HULK, HUNK, HUSK, GK, HQ, HG, JG, HAG, HOG, HUG, JAKE, HEX, HGT, JOKE, KC, KG, HAKKA, HOOKE, HAIKU, HOOKY, JACK, JOCK, JAG, JIG, JOG, JUG, KHAKI, HAYEK, HOICK, HOKEY, HICKOK, HQ'S, HG'S, HAJJ'S
hk	hijack	1	100	hijack, H, K, h, k, HQ, Hg, hake, hike, hoke, HI, Ha, He, Ho, ck, ha, he, hi, ho, wk, AK, Bk, Gk, HF, HM, HP, HR, HS, HT, Hf, Hz, Mk, OK, SK, UK, bk, hf, hp, hr, ht, pk, Huck, hack, hawk, heck, hick, hock, hook, hag, haj, hog, hug, Hakka, Hooke, haiku, hokey, hooky, KO, KY, Ky, kW, kw, KC, kc, kg, Hank, hank, hark, honk, hulk, hunk, husk, Hayek, hoick, Haw, Hay, Hui, haw, hay, hew, hex, hey, hgt, hie, hoe, how, hue, hwy, H's, Hugo, h'm, hgwy, huge, C, G, J, Q, c, g, j
sjk	hijack	4	44	SJ, SK, SJW, hijack, sqq, ska, ski, sky, Saki, sack, sake, seek, sick, soak, sock, souk, suck, SWAK, Saks, Salk, Sask, Sikh, sank, silk, sink, sulk, sunk, Gk, SC, Sc, Sq, jg, scag, sq, SAC, SEC, Sec, Soc, sac, sag, sec, seq, sic, soc
zphb	xenophobia	1	37	xenophobia, zephyr, Zibo, zebu, Sb, Zomba, sahib, soph, Feb, SOB, fab, fib, fob, sob, sub, AFB, phobia, Saab, Serb, scab, slab, slob, snob, snub, stab, stub, swab, FBI, SBA, Cebu, SF, Sophia, Sophie, sf, xv, Saiph, Sappho
zkw	zip line	1	67	zip line, kW, kw, Zeke, Zika, skew, SK, SJW, ska, ski, sky, wk, K, Z, k, z, Pkwy, pkwy, KS, Ks, ks, KO, KY, Ky, SW, ck, cw, skua, AK, Bk, Gk, KC, Mk, OK, UK, Zn, Zr, Zs, bk, kc, kg, pk, SC, SJ, Sc, Sq, sq, xx, Jew, KKK, SSW, WSW, Zoe, Zzz, caw, cow, jaw, jew, saw, sew, sow, zoo, Saki, Z's, sake, scow, K's
Joeuser	JoeUser	-1	-1
JoeuSer	JoeUser	-1	-1
JooUser	JoeUser	-1	-1
camelCasWord	camelCaseWord	-1	-1
camelcaseWord	camelCaseWord	-1	-1
cmlCaseWord	camelCaseWord	-1	-1
mcdonalds	McDonald's	1	4	McDonald's, McDonald, MacDonald's, MacDonald
