colour	color	1	61	color, cooler, collar, co lour, co-lour, col our, col-our, collier, colors, clout, lour, velour, cloud, colon, coolie, dolor, flour, Collier, clear, Clair, Colo, colder, calorie, closure, cloture, coleus, colony, colored, cool, glory, caller, cloy, clue, coir, coolers, Colon, col, color's, cor, cur, cools, floor, closer, clover, Cavour, Clojure, Closure, cola, coll, coolly, corr, cool's, recolor, Cole, COL, Clara, Clare, Col, Cooley, COLA, cooler's
hjk	hijack	1	55	hijack, hajj, hajji, Gk, haj, hack, hake, hawk, heck, hick, hike, hock, hoke, hook, hank, hark, honk, hulk, hunk, husk, jg, hag, hog, hug, hex, hgt, joke, Huck, Hank, kc, kg, HQ, Hg, haiku, hooky, jack, jock, Hakka, Hickok, jag, jig, jog, jug, khaki, Jake, hoick, hokey, KC, Hooke, Jack, Jock, hajj's, Hayek, HQ's, Hg's
hjkk	hijack	1	52	hijack, hajj, hajji, hulk, Hickok, hack, hake, hawk, heck, hick, hike, hock, hoke, hook, hank, hark, honk, hunk, husk, Hakka, Gk, haj, jack, jock, joke, Huck, Hank, jg, kc, kg, haiku, hoick, hokey, hooky, hag, hog, hug, jag, jig, jog, jug, khaki, Jack, Jake, Jock, hajj's, HQ, Hg, KC, Hayek, Hooke, Hakka's
jk	hijack	6	76	j, k, Gk, jg, joke, hijack, kc, kg, ck, wk, Bk, Mk, bk, jr, pk, jack, jock, jag, jig, jog, jug, Jake, KC, kike, JFK, Jack, Jock, QC, cg, J, K, Keck, jokey, kick, kl, kook, kW, keg, kw, Jo, km, ks, kt, AK, JD, JP, JV, Jr, OK, SK, UK, jerk, jink, junk, jaw, jay, jct, jew, joy, pkg, Coke, cake, coke, KKK, C, G, Jacky, Q, c, g, q, KO, KY, Ky, KB, KP
Hjk	Hijack	1	52	Hijack, Hajj, Hajji, Gk, Haj, Huck, Hack, Hake, Hawk, Heck, Hick, Hike, Hock, Hoke, Hook, Hank, Hark, Honk, Hulk, Hunk, Husk, HQ, Hg, Hakka, Hickok, Hag, Hog, Hug, Hex, Hgt, Jg, Hooke, Haiku, Hooky, Jake, Joke, Hayek, Hoick, Hokey, KC, Kc, Kg, HQ's, Hg's, Jack, Jock, Hajj's, Jag, Jig, Jog, Jug, Khaki
HJK	HIJACK	1	51	HIJACK, HAJJ, HAJJI, GK, HAJ, HUCK, HACK, HAKE, HAWK, HECK, HICK, HIKE, HOCK, HOKE, HOOK, HANK, HARK, HONK, HULK, HUNK, HUSK, HQ, HG, JG, HAKKA, HICKOK, HAG, HOG, HUG, JAKE, HEX, HGT, JOKE, KC, KG, HOOKE, JACK, JOCK, HAIKU, HOOKY, JAG, JIG, JOG, JUG, KHAKI, HAYEK, HOICK, HOKEY, HQ'S, HG'S, HAJJ'S
hk	hijack	1	63	hijack, Gk, h, k, haj, hake, hike, hoke, ck, ha, he, hi, ho, wk, Bk, HQ, Hg, Mk, bk, hf, hp, hr, ht, pk, hack, hawk, heck, hick, hock, hook, hag, hog, hug, Huck, H, K, kg, haiku, hokey, hooky, G, J, g, hgwy, j, kW, kw, HI, Ha, He, Ho, kc, AK, HF, HM, HP, HR, HS, HT, Hf, Hz, OK, SK
sjk	hijack	1	44	hijack, sqq, SJ, SK, ska, ski, sky, SJW, sack, sake, seek, sick, soak, sock, souk, suck, sank, silk, sink, sulk, sunk, Gk, jg, scag, sq, sac, sag, sec, seq, sic, soc, Saki, SWAK, Saks, Salk, Sask, Sikh, SC, Sc, Sq, SAC, SEC, Sec, Soc
zphb	xenophobia	1	37	xenophobia, zephyr, fob, sob, zebu, Sb, sahib, soph, Feb, Zomba, fab, fib, sub, xv, SOB, Zibo, phobia, Saab, Serb, scab, slab, slob, snob, snub, stab, stub, swab, AFB, Cebu, SF, Sophia, Sophie, sf, Saiph, FBI, SBA, Sappho
