colour	color	1	61	color, cooler, collar, co lour, co-lour, col our, col-our, colors, lour, collier, cloud, clout, colon, dolor, flour, clear, Colo, colder, closure, cloture, coleus, colony, velour, cool, caller, coolers, Collier, Colon, col, color's, colored, cor, cur, glory, Clair, cools, floor, closer, clover, calorie, Cavour, Clojure, Closure, cloy, clue, coir, cola, coll, coolie, coolly, corr, cool's, recolor, COL, Clara, Clare, Col, COLA, Cole, Cooley, cooler's
hjk	hijack	1	55	hijack, hajj, haj, hack, hake, hawk, heck, hick, hike, hock, hoke, hook, hajji, hank, hark, honk, hulk, hunk, husk, Gk, jg, hag, hog, hug, hex, hgt, joke, Huck, Hank, kc, kg, HQ, Hg, haiku, hooky, jack, jock, jag, jig, jog, jug, Jake, khaki, hoick, hokey, KC, Hakka, Hooke, Jack, Jock, Hayek, Hickok, HQ's, Hg's, hajj's
hjkk	hijack	1	52	hijack, hajj, hajji, Hickok, hack, hake, hawk, heck, hick, hike, hock, hoke, hook, hank, hark, honk, hulk, hunk, husk, Hakka, haj, jack, jock, joke, Huck, Hank, Gk, jg, kc, kg, haiku, hoick, hokey, hooky, hag, hog, hug, jag, jig, jog, jug, Jack, Jake, Jock, khaki, HQ, Hg, KC, Hayek, Hooke, hajj's, Hakka's
jk	hijack	6	76	j, k, Gk, jg, joke, hijack, kc, kg, ck, wk, Bk, Mk, bk, jr, pk, jack, jock, jag, jig, jog, jug, Jake, KC, JFK, Jack, Jock, QC, cg, J, K, jokey, kW, kw, Jo, keg, kl, km, ks, kt, AK, JD, JP, JV, Jr, OK, SK, UK, jerk, jink, junk, jaw, jay, jct, jew, joy, pkg, Coke, cake, coke, kike, C, G, Jacky, Q, c, g, q, KO, KY, Ky, KB, KP, KS, Kb, Kr, Ks
Hjk	Hijack	1	52	Hijack, Hajj, Haj, Huck, Hack, Hake, Hawk, Heck, Hick, Hike, Hock, Hoke, Hook, Hank, Hajji, Hark, Honk, Hulk, Hunk, Husk, Gk, HQ, Hg, Hag, Hog, Hug, Hex, Hgt, Jg, Hakka, Hooke, Haiku, Hooky, Jake, Joke, Hayek, Hoick, Hokey, Hickok, KC, Kc, Kg, HQ's, Hg's, Jack, Jock, Jag, Jig, Jog, Jug, Khaki, Hajj's
HJK	HIJACK	1	51	HIJACK, HAJJ, HAJ, HUCK, HACK, HAKE, HAWK, HECK, HICK, HIKE, HOCK, HOKE, HOOK, HANK, HAJJI, HARK, HONK, HULK, HUNK, HUSK, GK, HQ, HG, JG, HAG, HOG, HUG, JAKE, HEX, HGT, JOKE, KC, KG, HAKKA, HOOKE, HAIKU, HOOKY, JACK, JOCK, JAG, JIG, JOG, JUG, KHAKI, HAYEK, HOICK, HOKEY, HICKOK, HQ'S, HG'S, HAJJ'S
hk	hijack	1	62	hijack, h, k, hake, hike, hoke, ck, ha, he, hi, ho, wk, Bk, Gk, HQ, Hg, Mk, bk, hf, hp, hr, ht, pk, hack, hawk, heck, hick, hock, hook, hag, haj, hog, hug, Huck, H, K, haiku, hokey, hooky, kW, kw, HI, Ha, He, Ho, kc, kg, AK, HF, HM, HP, HR, HS, HT, Hf, Hz, OK, SK, UK, hank, hark, honk
sjk	hijack	1	44	hijack, sqq, SJ, SK, ska, ski, sky, SJW, sack, sake, seek, sick, soak, sock, souk, suck, sank, silk, sink, sulk, sunk, Gk, jg, scag, sq, sac, sag, sec, seq, sic, soc, Saki, SWAK, Saks, Salk, Sask, Sikh, SC, Sc, Sq, SAC, SEC, Sec, Soc
zphb	xenophobia	1	37	xenophobia, zephyr, zebu, Sb, sahib, soph, Feb, fab, fib, fob, sob, sub, Zibo, phobia, Saab, Serb, scab, slab, slob, snob, snub, stab, stub, swab, Zomba, SOB, AFB, Cebu, SF, Sophia, Sophie, sf, xv, Saiph, FBI, SBA, Sappho
