colour	color	1	59	color, cooler, collar, coLour, colOur, Collier, collier, colors, clout, Clair, Colo, lour, velour, Colon, cloud, colon, coolie, dolor, flour, clear, colder, Cavour, Clojure, Closure, calorie, closure, cloture, coleus, colony, colored, cool, glory, caller, Cole, cloy, clue, coir, coolers, COL, Clara, Clare, Col, col, color's, cor, cur, Cooley, cools, floor, closer, clover, COLA, cola, coll, coolly, corr, cool's, recolor, cooler's
hjk	hijack	1	55	hijack, hajj, hajji, Gk, haj, Huck, hack, hake, hawk, heck, hick, hike, hock, hoke, hook, Hank, hank, hark, honk, hulk, hunk, husk, HQ, Hg, jg, Hakka, Hickok, hag, hog, hug, Jake, hex, hgt, joke, KC, kc, kg, Hooke, Jack, Jock, haiku, hooky, jack, jock, jag, jig, jog, jug, khaki, Hayek, hoick, hokey, HQ's, Hg's, hajj's
hjkk	hijack	1	52	hijack, hajj, Hickok, hajji, Hakka, hulk, Huck, hack, hake, hawk, heck, hick, hike, hock, hoke, hook, Hank, hank, hark, honk, hunk, husk, Gk, haj, Jack, Jake, Jock, jack, jock, joke, HQ, Hg, KC, jg, kc, kg, Hayek, Hooke, haiku, hoick, hokey, hooky, hag, hog, hug, jag, jig, jog, jug, khaki, hajj's, Hakka's
jk	hijack	10	100	JFK, J, K, j, k, Gk, jg, Jake, joke, hijack, KC, kc, kg, Jo, ck, wk, AK, Bk, JD, JP, JV, Jr, Mk, OK, SK, UK, bk, jr, pk, Jack, Jock, jack, jock, jag, jig, jog, jug, kike, QC, cg, jK, KKK, Jacky, Keck, jokey, kick, kl, kook, KO, KY, Ky, kW, keg, kw, KB, KP, KS, Kb, Kr, Ks, km, ks, kt, jerk, jink, junk, DJ, NJ, OJ, SJ, VJ, EKG, JCS, Jay, Jew, Joe, Joy, jaw, jay, jct, jew, joy, pkg, Coke, J's, cake, coke, C, G, Q, c, g, q, Cook, cock, cook, gawk, geek, gook, K's
Hjk	Hijack	1	52	Hijack, Hajj, Hajji, Gk, Haj, Huck, Hack, Hake, Hawk, Heck, Hick, Hike, Hock, Hoke, Hook, Hank, Hark, Honk, Hulk, Hunk, Husk, HQ, Hg, Jg, Hakka, Hickok, Hag, Hog, Hug, Jake, Hex, Hgt, Joke, KC, Kc, Kg, Hooke, Jack, Jock, Haiku, Hooky, Jag, Jig, Jog, Jug, Khaki, Hayek, Hoick, Hokey, HQ's, Hg's, Hajj's
HJK	HIJACK	1	51	HIJACK, HAJJ, HAJJI, GK, HAJ, HUCK, HACK, HAKE, HAWK, HECK, HICK, HIKE, HOCK, HOKE, HOOK, HANK, HARK, HONK, HULK, HUNK, HUSK, HQ, HG, JG, HAKKA, HICKOK, HAG, HOG, HUG, JAKE, HEX, HGT, JOKE, KC, KG, HOOKE, JACK, JOCK, HAIKU, HOOKY, JAG, JIG, JOG, JUG, KHAKI, HAYEK, HOICK, HOKEY, HQ'S, HG'S, HAJJ'S
hk	hijack	1	100	hijack, Gk, H, K, h, k, HQ, Hg, haj, hake, hike, hoke, HI, Ha, He, Ho, ck, ha, he, hi, ho, wk, AK, Bk, HF, HM, HP, HR, HS, HT, Hf, Hz, Mk, OK, SK, UK, bk, hf, hp, hr, ht, pk, Huck, hack, hawk, heck, hick, hock, hook, hag, hog, hug, hK, kg, Hakka, Hooke, haiku, hokey, hooky, G, J, KO, KY, Ky, g, hgwy, j, kW, kw, KC, kc, Hank, hank, hark, honk, hulk, hunk, husk, Hayek, hoick, Haw, Hay, Hui, haw, hay, hew, hex, hey, hgt, hie, hoe, how, hue, hwy, H's, Hugo, h'm, huge, C, Q
sjk	hijack	4	44	SJ, SK, SJW, hijack, sqq, ska, ski, sky, Saki, sack, sake, seek, sick, soak, sock, souk, suck, SWAK, Saks, Salk, Sask, Sikh, sank, silk, sink, sulk, sunk, Gk, SC, Sc, Sq, jg, scag, sq, SAC, SEC, Sec, Soc, sac, sag, sec, seq, sic, soc
zphb	xenophobia	1	37	xenophobia, Zomba, zephyr, SOB, Zibo, fob, sob, zebu, Sb, sahib, soph, Feb, fab, fib, sub, AFB, xv, phobia, Saab, Serb, scab, slab, slob, snob, snub, stab, stub, swab, FBI, SBA, Cebu, SF, Sophia, Sophie, sf, Saiph, Sappho
zkw	zip line	1	68	zip line, kW, kw, Zeke, SJW, Zika, skew, SK, ska, ski, sky, zKw, wk, K, SJ, Sq, Z, k, sq, xx, z, Zoe, Pkwy, pkwy, sake, KS, Ks, ks, KO, KY, Ky, SW, ck, cw, skua, AK, Bk, Gk, KC, Mk, OK, UK, Zn, Zr, Zs, bk, kc, kg, pk, SC, Sc, Jew, KKK, SSW, WSW, Zzz, caw, cow, jaw, jew, saw, sew, sow, zoo, Saki, Z's, scow, K's
Joeuser	JoeUser	1	57	JoeUser, Jouster, Geyser, Mouser, Causer, Josue, Guesser, Kaiser, Courser, Grouser, Jester, Joeys, Juster, Kisser, Josher, Joust, Jeer, Juicer, User, Joyner, Dowser, Joiner, Jokier, Lousier, Mousier, Jesse, Joe's, Cozier, Josef, Joker, Loser, Poser, Jersey, Queasier, Jenner, Joey's, Mauser, Dosser, Gouger, Jobber, Jogger, Jotter, Leaser, Lesser, Looser, Teaser, Tosser, Caesar, Gasser, Coaxer, Geezer, Josue's, Accuser, Coarser, Coercer, Greaser, Jesse's
JoeuSer	JoeUser	1	57	JoeUser, Jouster, Geyser, Mouser, Causer, Josue, Guesser, Kaiser, Courser, Grouser, Jester, Joeys, Juster, Kisser, Josher, Joust, Jeer, Juicer, User, Joyner, Dowser, Joiner, Jokier, Lousier, Mousier, Jesse, Joe's, Cozier, Josef, Joker, Loser, Poser, Jersey, Queasier, Jenner, Joey's, Mauser, Dosser, Gouger, Jobber, Jogger, Jotter, Leaser, Lesser, Looser, Teaser, Tosser, Caesar, Gasser, Coaxer, Geezer, Josue's, Accuser, Coarser, Coercer, Greaser, Jesse's
JooUser	JoeUser	2	92	JoUser, JoeUser, JoyUser, CooUser, GooUser, KOUser, JobUser, JonUser, JogUser, JotUser, BooUser, FooUser, LooUser, MooUser, PooUser, TooUser, WooUser, ZooUser, JUser, JoeyUser, COUser, CoUser, GoUser, CoyUser, GAOUser, GeoUser, GoaUser, JayUser, JewUser, CowUser, JawUser, QuoUser, JoOUser, Jouster, Jo'sUser, Looser, Mouser, Hoosier, Causer, Grouser, Josue, Juicer, Kaiser, Joyous, Juster, Kisser, Josher, Joust, Poser, Chooser, User, Courser, Gooier, Joyner, Joiner, Jokier, Lousier, Mousier, Cozier, Geyser, Goose, Josef, Joker, Loser, Joyously, Grouse, Closer, Cooper, Mauser, Boozer, Cooker, Cooler, Dosser, Dowser, Goober, Goosed, Gooses, Gouger, Jobber, Jogger, Jotter, Oozier, Tosser, Gasser, Carouser, Coaxer, Josue's, Accuser, Coarser, Crosser, Grosser, Goose's
camelCasWord	camelCaseWord	3	100	camelCSSWord, camelCa'sWord, camelCaseWord, camelCawsWord, camelCaysWord, camelCabsWord, camelCadsWord, camelCamsWord, camelCansWord, camelCapsWord, camelCarsWord, camelCaskWord, camelCastWord, camelCatsWord, camelCADWord, camelCashWord, camelCsWord, camelCadWord, camelAsWord, camelCAWord, camelCaWord, camelC'sWord, camelCosWord, camelGasWord, camelCaSword, camelCauseWord, camelCussWord, camelCAIWord, camelCBSWord, camelCDsWord, camelCNSWord, camelCVSWord, camelCawWord, camelCayWord, camelCpsWord, camelCAMWord, camelCAPWord, camelCalWord, camelCanWord, camelLasWord, camelOASWord, camelCabWord, camelCamWord, camelCapWord, camelCarWord, camelCatWord, camelHasWord, camelMasWord, camelPasWord, camelWasWord, camelCaseyWord, camelGSAWord, camelCaw'sWord, camelCay'sWord, camelCO'sWord, camelCo'sWord, camelCu'sWord, camelGa'sWord, camelCoaxWord, camelCoosWord, camelCowsWord, camelCuesWord, camelGaysWord, camelJawsWord, camelJaysWord, camelCZWord, camelKSWord, camelKsWord, camelGsWord, camelCSS'sWord, camelCos'sWord, camelCoxWord, camelG'sWord, camelGusWord, camelJ'sWord, camelK'sWord, camelCAsWord, camelCaSWord, camelCPA'sWord, camelCIA'sWord, camelVa'sWord, camelGas'sWord, camelA'sWord, camelAC'sWord, camelAc'sWord, camelCAD'sWord, camelCal'sWord, camelCan'sWord, camelRCA'sWord, camelCab'sWord, camelCad'sWord, camelCam'sWord, camelCap'sWord, camelCar'sWord, camelCat'sWord, camelCD'sWord, camelCT'sWord, camelCd'sWord, camelCf'sWord, camelCl'sWord
camelcaseWord	camelCaseWord	1	13	camelCaseWord, camelsWord, camelliasWord, Camel'sWord, camel'sWord, CamelotsWord, camellia'sWord, Camilla'sWord, Camelot'sWord, Camille'sWord, Jamaica'sWord, Mameluke'sWord, gemologist
cmlCaseWord	camelCaseWord	8	56	XMLCaseWord, ClCaseWord, CmCaseWord, clCaseWord, cmCaseWord, mlCaseWord, CamelCaseWord, camelCaseWord, COLCaseWord, CalCaseWord, ColCaseWord, calCaseWord, colCaseWord, CplCaseWord, cplCaseWord, comelyCaseWord, cumuliCaseWord, calmCaseWord, cMlCaseWord, cmLCaseWord, CAMCaseWord, ComCaseWord, MelCaseWord, camCaseWord, comCaseWord, cumCaseWord, milCaseWord, OcamlCaseWord, COLACaseWord, CaliCaseWord, ColeCaseWord, ColoCaseWord, ComoCaseWord, callCaseWord, cameCaseWord, coalCaseWord, coilCaseWord, colaCaseWord, collCaseWord, comaCaseWord, combCaseWord, comeCaseWord, commCaseWord, coolCaseWord, cowlCaseWord, cullCaseWord, Cm'sCaseWord, JamalCaseWord, JamelCaseWord, GMCaseWord, QMCaseWord, gmCaseWord, klCaseWord, kmCaseWord, SGMLCaseWord, gemologist
mcdonalds	McDonald's	1	4	McDonald's, McDonald, MacDonald's, MacDonald
