colour	color	0	60	cooler, collar, co lour, co-lour, col our, col-our, Collier, collier, colors, clout, Clair, Colo, lour, velour, Colon, cloud, colon, coolie, dolor, flour, clear, colder, Cavour, Clojure, Closure, calorie, closure, cloture, coleus, colony, colored, cool, glory, caller, Cole, cloy, clue, coir, coolers, COL, Clara, Clare, Col, col, color's, cor, cur, Cooley, cools, floor, closer, clover, COLA, cola, coll, coolly, corr, cool's, recolor, cooler's
hjk	hijack	1	73	hijack, hajj, hajji, Gk, haj, Huck, hack, hake, hawk, heck, hick, hike, hock, hoke, hook, Hank, hank, hark, honk, hulk, hunk, husk, HQ, Hg, jg, Hakka, Hickok, hag, hog, hug, Jake, hex, hgt, joke, KC, kc, kg, Hooke, JFK, Jack, Jock, haiku, hooky, jack, jock, H, J, K, h, j, jag, jig, jog, jug, k, khaki, Hayek, hoick, hokey, HI, Ha, He, Ho, Jo, ck, ha, he, hi, ho, wk, HQ's, Hg's, hajj's
hjkk	hijack	1	54	hijack, hajj, Hickok, hajji, Hakka, hulk, Huck, hack, hake, hawk, heck, hick, hike, hock, hoke, hook, Hank, hank, hark, honk, hunk, husk, Gk, haj, KKK, Jack, Jake, Jock, jack, jock, joke, HQ, Hg, KC, jg, kc, kg, Hayek, Hooke, JFK, haiku, hoick, hokey, hooky, hag, hog, hug, jag, jig, jog, jug, khaki, hajj's, Hakka's
jk	hijack	21	76	JFK, J, K, j, k, Gk, jg, Jake, joke, KC, kc, kg, Jack, Jock, jack, jock, jag, jig, jog, jug, hijack, Jo, ck, wk, AK, Bk, JD, JP, JV, Jr, Mk, OK, SK, UK, bk, jr, kike, pk, QC, cg, KKK, Jacky, Keck, jokey, kick, kl, kook, KO, KY, Ky, kW, keg, kw, KB, KP, KS, Kb, Kr, Ks, km, ks, kt, jerk, jink, junk, DJ, NJ, OJ, SJ, VJ, EKG, JCS, Jay, Jew, Joe, Joy
Hjk	Hijack	1	64	Hijack, Hajj, Hajji, Gk, Haj, Huck, Hack, Hake, Hawk, Heck, Hick, Hike, Hock, Hoke, Hook, Hank, Hark, Honk, Hulk, Hunk, Husk, HQ, Hg, Jg, Hakka, Hickok, Hag, Hog, Hug, Jake, Hex, Hgt, Joke, KC, Kc, Kg, Hooke, JFK, Jack, Jock, Haiku, Hooky, H, J, K, Jag, Jig, Jog, Jug, Khaki, Hayek, Hoick, Hokey, HI, Ha, He, Ho, Jo, Ck, Hi, Wk, HQ's, Hg's, Hajj's
HJK	HIJACK	1	62	HIJACK, HAJJ, HAJJI, GK, HAJ, HUCK, HACK, HAKE, HAWK, HECK, HICK, HIKE, HOCK, HOKE, HOOK, HANK, HARK, HONK, HULK, HUNK, HUSK, HQ, HG, JG, HAKKA, HICKOK, HAG, HOG, HUG, JAKE, HEX, HGT, JOKE, KC, KG, HOOKE, JFK, JACK, JOCK, HAIKU, HOOKY, H, J, K, JAG, JIG, JOG, JUG, KHAKI, HAYEK, HOICK, HOKEY, HI, HA, HE, HO, JO, CK, WK, HQ'S, HG'S, HAJJ'S
hk	hijack	1	62	hijack, Gk, H, K, h, k, HQ, Hg, haj, hake, hike, hoke, Huck, hack, hawk, heck, hick, hock, hook, hag, hog, hug, HI, Ha, He, Ho, ck, ha, he, hi, ho, wk, AK, Bk, HF, HM, HP, HR, HS, HT, Hf, Hz, Mk, OK, SK, UK, bk, hf, hp, hr, ht, pk, kg, Hakka, Hooke, haiku, hokey, hooky, G, J, KO, KY
sjk	hijack	4	44	SJ, SK, SJW, hijack, sqq, ska, ski, sky, Saki, sack, sake, seek, sick, soak, sock, souk, suck, SWAK, Saks, Salk, Sask, Sikh, sank, silk, sink, sulk, sunk, Gk, SC, Sc, Sq, jg, scag, sq, SAC, SEC, Sec, Soc, sac, sag, sec, seq, sic, soc
zphb	xenophobia	1	100	xenophobia, Zomba, zephyr, SOB, Zibo, fob, pH, sob, zebu, Pb, Sb, phi, PHP, PhD, kph, mph, pub, sahib, soph, APB, PCB, Feb, fab, fib, sub, AFB, xv, hob, phobia, Saab, Serb, scab, slab, slob, snob, snub, stab, stub, swab, GB, HBO, Heb, OB, Ob, Zn, hub, ob, zap, zip, B, FBI, SBA, Z, b, z, phis, phys, Zoe, phew, zoo, Phil, chub, phat, BB, Cebu, AB, CB, Cb, HF, Hf, KB, Kb, MB, Mb, NB, Nb, QB, Rb, Sp, TB, Tb, Yb, Zr, Zs, ab, dB, db, hf, lb, pf, tb, vb, SF, Sophia, Sophie, sf, Caph, Saiph, BBB, GHz
