#!/bin/sh

set -e

make -C .. prep

for f in 00-special 02-orig 05-common
do
    for mode in ultra fast normal slow bad-spellers
    do
        echo "** $f $mode"
        time ./run-batch "../inst/bin/aspell --sug-mode=$mode" $f.tab $f-$mode-expect
    done
    for mode in ultra normal
    do
        echo "** $f $mode"
        time ./run-batch "../inst/bin/aspell --keyboard=none --sug-mode=$mode" $f.tab $f-$mode-nokbd-expect
    done
done
