#!/bin/sh

# Ispell compatibility script for Aspell

# Uncomment this (remove the leading '#') to use the Ispell key
#   mapping when checking files with the "ispell command".
#CHECK_FLAGS="--keymapping=ispell"

command=""

for p 
do
  case $p in 
  -a|-A|-l|-c|-e*|-v*|-D) command=$p ;; 
  -*                    ) ;;
  *                     ) command=${command:="-"} ;;
  esac
done

case $command in
-A          ) echo "Aspell does not support the $command mode.";;
-a|-v*      ) exec aspell "$@" ;;
-l          ) shift; exec aspell list "$@" ;;
-c          ) shift; exec aspell munch "$@" ;;
-e          ) shift; exec aspell expand "$@" ;;
-e?         ) shift; exec aspell expand `expr "x$command" : '...\(.\)'` "$@" ;;
-D          ) shift; exec aspell dump affix "$@" ;;
"-"         ) exec aspell check $CHECK_FLAGS "$@" ;;
*           ) echo "Ispell compatibility script for Aspell."
              echo "Usage: $0 [options] -a|-l|-v[v]|-c|-e[1-4]|<file>"
              exit 1 ;;
esac
